title: NeverOff Link Shortener
description: URL Shortener for NeverOff Dev, courtesy of <a href="https://github.com/hlaueriksson/jekyll-url-shortener" target="_blank" >Henrik Lau Eriksson</a>
logo: /assets/img/neveroff-logo.png
show_downloads: false
google_analytics: G-YQ40PX3B2Z
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

github: [metadata]
