title: NeverOff Link Shortener
description: URL Shortener for NeverOff Dev Projects, curtesy of https://github.com/hlaueriksson/jekyll-url-shortener
logo: /assets/img/neveroff-logo.png
show_downloads: true
google_analytics: G-YQ40PX3B2Z
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

github: [metadata]
